### ISSUE TITLE
spriteImagePath() returns incorrect path

### ISSUE THREAD

**Issue by shimonenator** [irok/sprite-magic-importer#3]
I've encountered that if you set `generated_images_dir` to a relative path, it would generate sprites in the `cwd` instead of relatively to the project. It looks like https://github.com/irok/sprite-magic-importer/blob/master/src/SpriteMagic.js#L363 should be using `this.options.generated_images_path` instead of `this.options.generated_images_dir`.

**Comment by irok** [comment]
@shimonenator Thank you for your advice.
I will investigate.
